### ISSUE TITLE
I'm a newbie?

### ISSUE THREAD

**Issue by AndreasBujok** [gtpy/ChameleonMini-RevG-GUI#4]
Hi @gtpy 

Can you provide a step by step docu about to install/start the GUI?
 I feel me a little bit alone. I've own a Chameleon Mini and now?!?

Thanks
Cheers Andreas

**Comment by gtpy** [comment]
I'll create a wiki soon.
For the beginning and easiest way you could use the released program v1.0.1
https://github.com/gtpy/ChameleonMini-RevG-GUI/releases
Otherwise you could compile from source e.g with visual studio.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 24. Feb. 2018, 17:15, Andreas Bujok schrieb:

**Comment by AndreasBujok** [comment]
Or can you also add a ready compiled binary for windows?

:-)

**Comment by gtpy** [comment]
Under the release you'll find a .zip file with an ready to use .exe file

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 24. Feb. 2018, 19:14, Andreas Bujok schrieb:

**Comment by AndreasBujok** [comment]
Hi.

 

got it. I'm not so familar with the differtend option/links/tan of github projects.

 

Thanks Andreas

 

 

Gesendet: Samstag, 24. Februar 2018 um 19:18 Uhr
Von: init0 <notifications@github.com>
An: gtpy/ChameleonMini-RevG-GUI <ChameleonMini-RevG-GUI@noreply.github.com>
Cc: "Andreas Bujok" <git@fine-photo.de>, Author <author@noreply.github.com>
Betreff: Re: [gtpy/ChameleonMini-RevG-GUI] I'm a newbie? (#4)

Under the release you'll find a .zip file with an ready to use .exe file

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 24. Feb. 2018, 19:14, Andreas Bujok schrieb:

**Comment by gtpy** [comment]
Great. No problem. 
If you have any further questions open an issue ;-)
